# Generated by Django 2.2.28 on 2023-03-20 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('pastAddress', models.TextField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('rent', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('check', 'Check')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.Client')),
                ('lease_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.LeaseAgreement')),
            ],
        ),
        migrations.CreateModel(
            name='PackageSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_subscription', to='main.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50)),
                ('delivered', models.BooleanField(default=False)),
                ('leaseAgreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_agreement', to='main.LeaseAgreement')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='main.PackageSubscription')),
            ],
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_agreements', to='main.Manager'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Property'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='complaints/')),
                ('resolved', models.BooleanField(default=False)),
                ('reply', models.TextField(blank=True, null=True)),
                ('leaseAgreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='main.LeaseAgreement')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement', to='main.Manager')),
            ],
        ),
    ]
