# Generated by Django 4.0.8 on 2023-04-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='image',
            field=models.FileField(blank=True, upload_to='agreements/'),
        ),
    ]
