# Generated by Django 4.0.8 on 2023-04-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_leaseagreement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaseagreement',
            old_name='image',
            new_name='agreement',
        ),
    ]
